2015/05/03 18:45:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login.dofit".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('login.dofit')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('login.dofit')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.dofi...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/login.dofit
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/contact.dofit
---
2015/05/03 18:56:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.damianGato".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('index.damianGat...')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('index.damianGat...')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.dami...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/index.damianGato
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/page.damianGato?view=about
---
2015/05/03 18:56:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.damianGato".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('index.damianGat...')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('index.damianGat...')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.dami...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/index.damianGato
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/page.damianGato?view=about
---
2015/05/03 18:56:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.damianGato".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('index.damianGat...')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('index.damianGat...')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.dami...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/index.damianGato
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/page.damianGato?view=about
---
2015/05/03 18:57:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.htmdamiangato".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('index.htmdamian...')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('index.htmdamian...')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.htmd...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/index.htmdamiangato
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/login.htmdamiangato
---
2015/05/10 18:32:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 18:32:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/index".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/index')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/index
---
2015/05/10 18:33:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 18:40:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 18:40:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/index".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/index')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/index
---
2015/05/10 19:00:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 19:01:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/index".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/index')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/index
---
2015/05/10 19:01:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/login
---
2015/05/10 19:02:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/index".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/index')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/index.php
---
2015/05/10 19:03:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 19:33:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 19:33:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 19:38:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 19:38:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 19:38:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "viejo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('viejo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/viejo
---
2015/05/10 20:15:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 20:16:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 20:18:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 20:59:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 20:59:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 21:00:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 21:00:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/
---
2015/05/10 21:01:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 21:01:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola.php".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola.php')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola.php
---
2015/05/10 21:26:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/dofit/aplication/index.php?r=nuevo/hola
---
2015/05/10 21:31:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/dofit/aplication/index.php?r=nuevo/hol
---
2015/05/10 21:44:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/dofit/aplication/nuevo/hol
---
2015/05/10 21:44:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/nuevo/hol
---
2015/05/10 21:45:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/nuevo/hol
---
2015/05/10 21:45:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/site/login
---
2015/05/10 21:47:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/site/login
---
2015/05/10 21:47:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/site/login
---
2015/05/10 21:48:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/nuevo/hol
---
2015/05/13 04:25:45 [error] [exception.CException] exception 'CException' with message 'Property "User.create_time" is not defined.' in C:\xampp\htdocs\DoFit\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\db\ar\CActiveRecord.php(145): CComponent->__get('create_time')
#1 C:\xampp\htdocs\DoFit\framework\base\CComponent.php(612) : eval()'d code(1): CActiveRecord->__get('create_time')
#2 C:\xampp\htdocs\DoFit\framework\base\CComponent.php(612): eval()
#3 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CDataColumn.php(142): CComponent->evaluateExpression('date("M j, Y", ...', Array)
#4 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridColumn.php(231): CDataColumn->getDataCellContent(0)
#5 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridColumn.php(154): CGridColumn->renderDataCellContent(0, Object(User))
#6 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(638): CGridColumn->renderDataCell(0)
#7 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(622): CGridView->renderDataCell(Object(CDataColumn), 0)
#8 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(578): CGridView->renderTableRow(0)
#9 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(488): CGridView->renderTableBody()
#10 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(181): CGridView->renderItems()
#11 [internal function]: CBaseListView->renderSection(Array)
#12 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{item...')
#13 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#14 C:\xampp\htdocs\DoFit\framework\web\CBaseController.php(181): CBaseListView->run()
#15 C:\xampp\htdocs\DoFit\aplication\protected\controllers\SiteController.php(126): CBaseController->widget('zii.widgets.gri...', Array)
#16 C:\xampp\htdocs\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionHol()
#17 C:\xampp\htdocs\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(282): CController->run('hol')
#21 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hol')
#22 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/DoFit/aplication/site/hol
HTTP_REFERER=http://localhost/DoFit/aplication/
---
2015/05/13 04:27:24 [error] [exception.CException] exception 'CException' with message 'Property "User.create_time" is not defined.' in C:\xampp\htdocs\DoFit\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\db\ar\CActiveRecord.php(145): CComponent->__get('create_time')
#1 C:\xampp\htdocs\DoFit\framework\base\CComponent.php(612) : eval()'d code(1): CActiveRecord->__get('create_time')
#2 C:\xampp\htdocs\DoFit\framework\base\CComponent.php(612): eval()
#3 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CDataColumn.php(142): CComponent->evaluateExpression('date("M j, Y", ...', Array)
#4 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridColumn.php(231): CDataColumn->getDataCellContent(0)
#5 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridColumn.php(154): CGridColumn->renderDataCellContent(0, Object(User))
#6 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(638): CGridColumn->renderDataCell(0)
#7 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(622): CGridView->renderDataCell(Object(CDataColumn), 0)
#8 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(578): CGridView->renderTableRow(0)
#9 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(488): CGridView->renderTableBody()
#10 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(181): CGridView->renderItems()
#11 [internal function]: CBaseListView->renderSection(Array)
#12 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{item...')
#13 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#14 C:\xampp\htdocs\DoFit\framework\web\CBaseController.php(181): CBaseListView->run()
#15 C:\xampp\htdocs\DoFit\aplication\protected\controllers\SiteController.php(126): CBaseController->widget('zii.widgets.gri...', Array)
#16 C:\xampp\htdocs\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionHol()
#17 C:\xampp\htdocs\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(282): CController->run('hol')
#21 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hol')
#22 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/DoFit/aplication/site/hol
HTTP_REFERER=http://localhost/DoFit/aplication/
---
2015/06/02 02:46:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/gridViewStyle/images/gr-view.png".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('css/gridViewSty...')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/css/gridViewStyle/images/gr-view.png
HTTP_REFERER=http://localhost/DoFit/aplication/site/hol
---
2015/06/02 02:46:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/gridViewStyle/images/gr-update.png".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('css/gridViewSty...')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/css/gridViewStyle/images/gr-update.png
HTTP_REFERER=http://localhost/DoFit/aplication/site/hol
---
2015/06/02 02:46:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/gridViewStyle/images/gr-delete.png".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('css/gridViewSty...')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/css/gridViewStyle/images/gr-delete.png
HTTP_REFERER=http://localhost/DoFit/aplication/site/hol
---
<<<<<<< HEAD
2015/06/09 05:14:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "view".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/view/id/1')
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/view/id/1
HTTP_REFERER=http://127.0.0.1/DOFIT_FINAL/DoFit/aplication/site/hol
---
2015/06/09 05:14:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "update".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(270): CController->missingAction('update')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('update')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/update/id/...')
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/update/id/1
HTTP_REFERER=http://127.0.0.1/DOFIT_FINAL/DoFit/aplication/site/hol
---
2015/06/09 05:16:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "update".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(270): CController->missingAction('update')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('update')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/update/id/...')
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/update/id/1
HTTP_REFERER=http://127.0.0.1/DOFIT_FINAL/DoFit/aplication/site/hol
---
2015/06/09 05:23:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "r=gii".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('r=gii')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/r=gii
=======
2015/06/13 06:34:57 [error] [php] include(Usuario.php): failed to open stream: No such file or directory (C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\components\UserIdentity.php(20): spl_autoload_call()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CWebApplication->run()
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/login
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\components\UserIdentity.php (20)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php (94)
2015/06/13 07:02:45 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dofit.df_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `df_user`.
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php (144)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/13 07:02:45 [error] [exception.CDbException] exception 'CDbException' with message 'The table "df_user" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1606): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(147): CGridView->init()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(144): CBaseController->widget('zii.widgets.gri...', Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionHol()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('hol')
#17 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hol')
#18 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#19 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/hol
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/
---
2015/06/13 07:05:37 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\helpers\CHtml.php:2798)
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\views\site\login.php(51): link()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(95): SiteController->renderInternal()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(869): SiteController->renderFile()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(782): SiteController->renderPartial()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(98): SiteController->render()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CWebApplication->run()
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/login
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\views\site\login.php (51)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php (98)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/13 07:05:43 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\helpers\CHtml.php:2798)
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\views\site\login.php(51): link()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(95): SiteController->renderInternal()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(869): SiteController->renderFile()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(782): SiteController->renderPartial()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(98): SiteController->render()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CWebApplication->run()
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/login
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\views\site\login.php (51)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php (98)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/13 07:14:15 [error] [exception.CException] exception 'CException' with message 'Usuario and its behaviors do not have a method or closure named "disableDefaultScope".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(227): CComponent->__call('disableDefaultS...', Array)
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\components\UserIdentity.php(20): CActiveRecord->__call('disableDefaultS...', Array)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\components\UserIdentity.php(20): Usuario->disableDefaultScope()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(94): CModel->validate()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('login')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/login
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 07:15:31 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.email" is not defined.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\components\UserIdentity.php(20): CComponent->__get('email')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/login
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 07:16:02 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity._id" is not defined.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\components\UserIdentity.php(27): CComponent->__set('_id', '1')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/login
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 07:34:45 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dofit.df_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `df_user`.
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php (144)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/13 07:34:45 [error] [exception.CDbException] exception 'CDbException' with message 'The table "df_user" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1606): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(147): CGridView->init()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(144): CBaseController->widget('zii.widgets.gri...', Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionHol()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('hol')
#17 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hol')
#18 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#19 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/hol
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 07:36:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(270): CController->missingAction('usuario')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('usuario')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuario')
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/usuario
---
2015/06/13 07:36:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(270): CController->missingAction('usuario')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('usuario')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuario/in...')
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/usuario/index
---
2015/06/13 07:41:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create.php".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(270): CController->missingAction('create.php')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create.php')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create....')
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create.php
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 07:47:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "aplication/usuario/create".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('aplication/usua...')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 07:48:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "aplication/usuario/create".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('aplication/usua...')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 07:50:12 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dofit.df_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `df_user`.
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php (144)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/13 07:50:12 [error] [exception.CDbException] exception 'CDbException' with message 'The table "df_user" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1606): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(147): CGridView->init()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(144): CBaseController->widget('zii.widgets.gri...', Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionHol()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('hol')
#17 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hol')
#18 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#19 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/hol
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/
---
2015/06/13 07:51:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(270): CController->missingAction('usuario')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('usuario')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuario/in...')
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/usuario/index
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 07:51:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "usuario".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(270): CController->missingAction('usuario')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('usuario')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/usuario/in...')
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/usuario/index
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 19:08:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/admin')
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/admin
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/index
---
2015/06/13 19:08:41 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/admin')
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/admin
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/index
---
2015/06/13 19:10:14 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/admin')
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/admin
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/13 19:33:15 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/admin')
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/admin
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/13 19:35:23 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/admin')
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/admin
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
>>>>>>> 6ba62be06375680b5bc10083e0b5ceafe9430782
---
2015/06/14 19:59:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "config/main.php".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('config/main.php')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/config/main.php
---
2015/06/14 19:59:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "main.php".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('main.php')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/main.php
---
2015/06/16 05:01:15 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto_rober@yahoo.com.ar' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (110)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 05:01:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto_rober@yahoo.com.ar' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(110): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 05:47:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (95)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 05:47:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(95): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:01:08 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (94)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 06:01:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(94): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:03:28 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '56@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (94)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 06:03:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '56@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(94): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:05:05 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '47@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (94)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 06:05:05 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '47@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(94): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:05:16 [error] [exception.CException] exception 'CException' with message 'Property "FichaUsuario.Cusuario" is not defined.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(161): CComponent->__set('Cusuario', '7@gmail.com')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(99): CActiveRecord->__set('Cusuario', '7@gmail.com')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:09:47 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (102)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 06:09:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(102): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:11:05 [error] [exception.CException] exception 'CException' with message 'Property "Usuario.id_Usuario" is not defined.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id_Usuario')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(88): CActiveRecord->__get('id_Usuario')
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:12:51 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto_rober@yahoo.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (101)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 06:12:51 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto_rober@yahoo.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(101): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:18:19 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto_rober@yaho.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (102)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 06:18:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto_rober@yaho.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(102): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:19:17 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto1|_rober@yaho.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (102)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 06:19:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto1|_rober@yaho.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(102): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/16 06:19:38 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto1|_rober@yaho.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (102)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/16 06:19:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'monto1|_rober@yaho.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(102): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 05:16:49 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pepe@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (101)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/17 05:16:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pepe@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(101): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 05:17:13 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (101)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/17 05:17:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(101): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 06:29:44 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '34@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (95)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/17 06:29:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '34@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(95): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 06:42:55 [error] [php] Object of class Usuario could not be converted to string (C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php:110)
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): UsuarioController->runAction()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): UsuarioController->filterAccessControl()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): UsuarioController->runActionWithFilters()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): UsuarioController->run()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CWebApplication->run()
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (110)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/17 18:02:19 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pepe122@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (104)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/17 18:02:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pepe122@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(104): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 18:06:58 [error] [exception.CException] exception 'CException' with message 'Usuario and its behaviors do not have a method or closure named "findByAtttributes".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(227): CComponent->__call('findByAtttribut...', Array)
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(109): CActiveRecord->__call('findByAtttribut...', Array)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(109): Usuario->findByAtttributes(Array)
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 18:07:16 [error] [exception.CException] exception 'CException' with message 'Usuario and its behaviors do not have a method or closure named "findByAtttributes".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(227): CComponent->__call('findByAtttribut...', Array)
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(109): CActiveRecord->__call('findByAtttribut...', Array)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(109): Usuario->findByAtttributes(Array)
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 18:29:58 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pepe13435@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (107)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/17 18:29:58 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pepe13435@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(107): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 18:33:55 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php:97)
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): UsuarioController->runAction()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): UsuarioController->filterAccessControl()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): UsuarioController->runActionWithFilters()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): UsuarioController->run()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CWebApplication->run()
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (97)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/17 18:40:11 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php:97)
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): UsuarioController->runAction()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): UsuarioController->filterAccessControl()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): UsuarioController->runActionWithFilters()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): UsuarioController->run()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CWebApplication->run()
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (97)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/17 18:40:35 [error] [exception.CException] exception 'CException' with message 'FichaUsuario and its behaviors do not have a method or closure named "setAtrribute".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(227): CComponent->__call('setAtrribute', Array)
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(112): CActiveRecord->__call('setAtrribute', Array)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(112): FichaUsuario->setAtrribute('id_usuario', '62')
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 18:41:08 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pepe134444@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (104)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/17 18:41:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'pepe134444@gmail.com' for key 'email'. The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(104): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/17 18:57:35 [error] [php] Attempt to assign property of non-object (C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php:114)
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): UsuarioController->runAction()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): UsuarioController->filterAccessControl()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): UsuarioController->runActionWithFilters()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): UsuarioController->run()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CWebApplication->run()
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (114)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/18 05:09:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No se puede establecer una conexi�n ya que el equipo de destino deneg� expresamente dicha conexi�n.
' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(2384): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Usuario))
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(66): CActiveRecord->__construct()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#19 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#20 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#21 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/18 05:09:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No se puede establecer una conexi�n ya que el equipo de destino deneg� expresamente dicha conexi�n.
' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\views\usuario\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(176): CController->render('index', Array)
#21 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionIndex()
#22 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/index')
#32 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/index
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/20 04:50:28 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dofit`.`usuario`, CONSTRAINT `usuario_estado_fk` FOREIGN KEY (`id_estado`) REFERENCES `estado` (`id_estado`)). The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (109)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/20 04:50:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dofit`.`usuario`, CONSTRAINT `usuario_estado_fk` FOREIGN KEY (`id_estado`) REFERENCES `estado` (`id_estado`)). The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(109): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
2015/06/20 04:59:11 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dofit`.`usuario`, CONSTRAINT `usuario_estado_fk` FOREIGN KEY (`id_estado`) REFERENCES `estado` (`id_estado`)). The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `id_estado`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6).
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php (110)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/20 04:59:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dofit`.`usuario`, CONSTRAINT `usuario_estado_fk` FOREIGN KEY (`id_estado`) REFERENCES `estado` (`id_estado`)). The SQL statement executed was: INSERT INTO `usuario` (`fhultmod`, `email`, `password`, `id_perfil`, `id_estado`, `fhcreacion`, `cusuario`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6)' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\UsuarioController.php(110): CActiveRecord->save()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): UsuarioController->actionCreate()
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('create')
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/create')
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/usuario/create
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/create
---
<<<<<<< HEAD
2015/06/20 05:34:41 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dofit.df_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `df_user`.
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php (144)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/20 05:34:41 [error] [exception.CDbException] exception 'CDbException' with message 'The table "df_user" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php:2385
=======
2015/06/20 05:34:57 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dofit.df_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `df_user`.
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php (144)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/20 05:34:57 [error] [exception.CDbException] exception 'CDbException' with message 'The table "df_user" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php:2385
>>>>>>> 59ce1f70a850bde8490c1437b5b8290736b704af
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1606): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(147): CGridView->init()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(144): CBaseController->widget('zii.widgets.gri...', Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionHol()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('hol')
#17 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hol')
#18 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#19 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/hol
<<<<<<< HEAD
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/login
---
2015/06/20 05:34:55 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dofit.df_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `df_user`.
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php (144)
in C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php (13)
2015/06/20 05:34:55 [error] [exception.CDbException] exception 'CDbException' with message 'The table "df_user" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\db\ar\CActiveRecord.php(1606): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#4 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#5 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#6 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#7 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#8 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#9 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(147): CGridView->init()
#10 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#11 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\protected\controllers\SiteController.php(144): CBaseController->widget('zii.widgets.gri...', Array)
#12 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionHol()
#13 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(282): CController->run('hol')
#17 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hol')
#18 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#19 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/site/hol
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/site/index
---
2015/06/20 05:50:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "SiteController/actionLogin".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/
---
2015/06/20 05:51:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "SiteController/Login".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/
---
2015/06/20 05:51:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "SiteController/login".' in C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#1 C:\xampp\htdocs\DOFIT_FINAL\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DOFIT_FINAL\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DOFIT_FINAL/DoFit/aplication/
=======
HTTP_REFERER=http://localhost/DOFIT_FINAL/DoFit/aplication/usuario/index
>>>>>>> 59ce1f70a850bde8490c1437b5b8290736b704af
---
